name: testing-on-pullrequest

on: 
    pull_request:
        branches: [master]
jobs:
    unittest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 14.x
            - name: setup
              run: |
                npm install yarn -g
                yarn
            - name: unittest
              run: yarn test