name: testing-on-pullrequest

on: 
    pull_request:
        branches: [master]
jobs:
    unittest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 14.x
            - name: Configure AWS credentials from Test account
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-northeast-1          
            - name: setup
              run: |
                npm install yarn -g
                yarn
            - name: unittest
              run: yarn test